export interface ContentBlock {
  type: "text" | "callout" | "key_term" | "step_by_step" | "comparison" | "activity" | "summary" | "image";
  title?: string;
  content?: string;
  items?: string[];
  columns?: { left: string[]; right: string[]; leftTitle?: string; rightTitle?: string };
  variant?: "info" | "tip" | "warning" | "fun_fact";
  icon?: string;
  imageSrc?: string;
  imageAlt?: string;
}

export interface SampleChapter {
  classNum: number;
  title: string;
  subtitle: string;
  blocks: ContentBlock[];
}

export const sampleBookChapters: SampleChapter[] = [
  {
    classNum: 3,
    title: "Meet the Computer",
    subtitle: "Your New Digital Friend!",
    blocks: [
      { type: "text", title: "What is a Computer?", content: "A computer is an electronic machine that helps us do many things — like drawing, writing stories, playing games, watching videos, and even talking to friends far away! Just like how we use our brain to think and solve problems, a computer uses its own 'brain' called a processor to follow instructions and get things done really fast." },
      { type: "image", imageSrc: "/images/thinking-brain.png", imageAlt: "A colorful illustration of a brain connected to a computer", title: "The Computer Brain" },
      { type: "callout", variant: "fun_fact", content: "Did you know? The first computer was so big that it filled an entire room — bigger than your classroom! Today, computers are small enough to fit in your pocket (like a smartphone).", icon: "🤯" },
      { type: "key_term", title: "Processor (CPU)", content: "The 'brain' of the computer that thinks and works very fast. CPU stands for Central Processing Unit." },
      { type: "text", title: "Parts of a Computer", content: "Just like our body has different parts — eyes to see, ears to hear, hands to touch — a computer also has different parts that help it work. Let's learn about each one!" },
      { type: "step_by_step", title: "Main Parts of a Computer", items: ["Monitor — The screen where you see everything. It's like the computer's face!", "Keyboard — Has buttons with letters, numbers, and symbols. You type using it, just like writing in a notebook.", "Mouse — A small device you move around to point and click on things on the screen.", "CPU (System Unit) — The box that contains the computer's brain and memory. It does all the thinking!", "Speakers — Let you hear sounds, music, and voices from the computer."] },
      { type: "comparison", title: "Input vs Output Devices", columns: { leftTitle: "Input Devices (We give information)", rightTitle: "Output Devices (Computer gives us results)", left: ["Keyboard — we type letters", "Mouse — we click and point", "Microphone — we speak into it", "Camera — we show our face"], right: ["Monitor — we see pictures and text", "Speakers — we hear sounds", "Printer — we get papers printed", "Headphones — we hear privately"] } },
      { type: "callout", variant: "tip", content: "Easy way to remember: INPUT means 'going IN to the computer' and OUTPUT means 'coming OUT from the computer'!", icon: "💡" },
      { type: "key_term", title: "Hardware", content: "The parts of a computer you can touch and feel — like the keyboard, mouse, and monitor. They are the physical parts." },
      { type: "key_term", title: "Software", content: "The programs and apps inside the computer that you cannot touch — like games, drawing apps, and web browsers. They are the instructions that tell hardware what to do." },
      { type: "activity", title: "Quick Activity: Computer Parts Hunt!", content: "Look around your home or school. Can you find these computer parts? Make a list! Write down each part you find and whether it is an INPUT device or an OUTPUT device.", items: ["Monitor/Screen", "Keyboard", "Mouse or Touchpad", "Speakers or Headphones", "Printer (if available)"] },
      { type: "text", title: "Computers Are Everywhere!", content: "Computers are not just desktops and laptops! They are inside many things we use every day — smartphones, tablets, smart TVs, washing machines, and even cars! Any device that follows instructions and processes information has a tiny computer inside it." },
      { type: "summary", title: "Chapter Summary", content: "In this chapter, we learned that a computer is an electronic machine with different parts. Input devices help us send information to the computer, and output devices help the computer show us results. The CPU is the brain, and we can divide computer parts into hardware (things we touch) and software (programs we use)." }
    ]
  },
  {
    classNum: 4,
    title: "Patterns Around Us",
    subtitle: "Discovering Sequences & Repetition",
    blocks: [
      { type: "text", title: "What Are Patterns?", content: "Patterns are things that repeat in a predictable way. You see patterns everywhere — in the tiles on your floor, the stripes on a zebra, the petals of a flower, and even in the songs you sing! Recognizing patterns is one of the most important skills in computing and mathematics." },
      { type: "image", imageSrc: "/images/nature-patterns.png", imageAlt: "Beautiful patterns found in nature — spirals, symmetry, and fractals", title: "Patterns in Nature" },
      { type: "callout", variant: "fun_fact", content: "Nature is full of patterns! Sunflowers arrange their seeds in a special spiral pattern called the Fibonacci sequence. Each number is the sum of the two before it: 1, 1, 2, 3, 5, 8, 13...", icon: "🌻" },
      { type: "key_term", title: "Pattern", content: "A set of shapes, colors, numbers, or actions that repeat in a regular and predictable way. Patterns help us predict what comes next." },
      { type: "text", title: "Types of Patterns", content: "Patterns can be found in many forms. Some are visual (like colors and shapes), some are numerical (like counting sequences), and some are even in sounds and movements!" },
      { type: "step_by_step", title: "Types of Patterns We See", items: ["Color Patterns — Red, Blue, Red, Blue, Red, Blue... What comes next? Red!", "Shape Patterns — Circle, Square, Triangle, Circle, Square, Triangle... What comes next?", "Number Patterns — 2, 4, 6, 8, 10... Each number increases by 2!", "Sound Patterns — Clap, Clap, Snap, Clap, Clap, Snap... A rhythm!", "Action Patterns — Jump, Sit, Jump, Sit... A repeating movement!"] },
      { type: "comparison", title: "Repeating vs Growing Patterns", columns: { leftTitle: "Repeating Patterns", rightTitle: "Growing Patterns", left: ["Same group repeats over and over", "AB, AB, AB, AB...", "Red, Blue, Red, Blue...", "Easy to spot the repeating unit"], right: ["Pattern changes by adding more each time", "A, AB, ABC, ABCD...", "1, 3, 6, 10, 15...", "Each step builds on the previous one"] } },
      { type: "key_term", title: "Sequence", content: "An ordered list of numbers or items that follow a specific rule. For example: 5, 10, 15, 20 is a sequence where we add 5 each time." },
      { type: "text", title: "Patterns in Coding", content: "Computers love patterns! When programmers write code, they use patterns called 'loops' to repeat instructions. Instead of writing the same instruction 100 times, they tell the computer: 'Repeat this 100 times!' This makes coding faster and smarter." },
      { type: "callout", variant: "tip", content: "Think of patterns like a recipe. Once you know the pattern (recipe), you can repeat it as many times as you want without thinking too hard!", icon: "🍳" },
      { type: "activity", title: "Activity: Create Your Own Pattern!", content: "Use colored pencils or crayons to create three different patterns. Try making one repeating pattern and one growing pattern. Share your patterns with a friend and see if they can figure out the rule!", items: ["Draw a repeating color pattern with at least 3 colors", "Draw a growing pattern using shapes (start with 1, then 2, then 3...)", "Write a number pattern and challenge your friend to find the next 3 numbers"] },
      { type: "summary", title: "Chapter Summary", content: "Patterns are repeated arrangements that help us predict what comes next. They can be found in colors, shapes, numbers, sounds, and actions. Repeating patterns repeat the same group, while growing patterns add more each time. Computers use patterns (loops) to work efficiently!" }
    ]
  },
  {
    classNum: 5,
    title: "Thinking Like a Computer",
    subtitle: "Introduction to Computational Thinking",
    blocks: [
      { type: "text", title: "What is Computational Thinking?", content: "Computational Thinking (CT) is a way of solving problems step by step — just like a computer does! But you don't need a computer to use it. You can use computational thinking to solve everyday problems like organizing your school bag, planning a birthday party, or even making a sandwich!" },
      { type: "image", imageSrc: "/images/ct-pillars.png", imageAlt: "The four pillars of computational thinking illustrated", title: "Four Pillars of CT" },
      { type: "callout", variant: "info", content: "Computational Thinking is not about thinking like a robot. It's about breaking big problems into smaller, manageable pieces and finding smart solutions — something humans are naturally great at!", icon: "🧠" },
      { type: "key_term", title: "Computational Thinking", content: "A problem-solving approach that involves breaking problems down, finding patterns, focusing on what's important, and creating step-by-step solutions." },
      { type: "text", title: "The Four Pillars of Computational Thinking", content: "Computational Thinking has four main skills, often called 'pillars.' Think of them as four superpowers that help you solve any problem!" },
      { type: "step_by_step", title: "The Four Pillars", items: ["Decomposition — Breaking a big problem into smaller, easier parts. Like dividing a big project into small tasks.", "Pattern Recognition — Finding similarities or repeating elements. Like noticing that all math word problems follow a similar structure.", "Abstraction — Focusing on what's important and ignoring unnecessary details. Like reading a map — you don't need every tree, just the roads!", "Algorithm Design — Creating step-by-step instructions to solve the problem. Like writing a recipe that anyone can follow."] },
      { type: "comparison", title: "With vs Without Computational Thinking", columns: { leftTitle: "Without CT (Confused!)", rightTitle: "With CT (Organized!)", left: ["\"This project is too big!\"", "\"I don't know where to start\"", "\"Everything seems important\"", "\"I'll just figure it out as I go\""], right: ["\"Let me break it into 5 small tasks\"", "\"I'll start with the easiest part first\"", "\"Let me focus on the key details\"", "\"Here's my step-by-step plan\""] } },
      { type: "callout", variant: "fun_fact", content: "Even making a cup of tea uses computational thinking! You decompose the task (get cup, boil water, add tea bag), follow a pattern (you've done it before!), abstract away unimportant details (the color of the cup doesn't matter), and follow an algorithm (step-by-step instructions).", icon: "☕" },
      { type: "key_term", title: "Algorithm", content: "A set of clear, step-by-step instructions to solve a problem or complete a task. Algorithms must be precise so anyone (or any computer) can follow them." },
      { type: "key_term", title: "Decomposition", content: "Breaking a complex problem into smaller, more manageable sub-problems. Each small part is easier to understand and solve." },
      { type: "activity", title: "Activity: Decompose Your Morning Routine!", content: "Think about everything you do from waking up to reaching school. Break it down into at least 8 steps. Then identify any patterns (things you do the same way every day) and any steps you could skip (abstraction)!", items: ["Write down every single step of your morning", "Circle the steps that repeat every single day (patterns)", "Cross out any steps that aren't absolutely necessary (abstraction)", "Number your final steps in order (algorithm!)"] },
      { type: "text", title: "CT in Real Life", content: "Computational thinking isn't just for computers — doctors use it to diagnose diseases, architects use it to design buildings, chefs use it to create recipes, and detectives use it to solve mysteries! It's a universal problem-solving skill." },
      { type: "summary", title: "Chapter Summary", content: "Computational Thinking is a powerful problem-solving method with four pillars: Decomposition (break it down), Pattern Recognition (find similarities), Abstraction (focus on what matters), and Algorithm Design (create step-by-step solutions). These skills help in coding, school, and everyday life!" }
    ]
  },
  {
    classNum: 6,
    title: "Introduction to Algorithms",
    subtitle: "Step-by-Step Problem Solving",
    blocks: [
      { type: "text", title: "What is an Algorithm?", content: "An algorithm is a set of clear, precise, step-by-step instructions to solve a problem or complete a task. Think of it as a recipe — just like a cooking recipe tells you exactly what ingredients to use and what steps to follow, an algorithm tells a computer exactly what to do and in what order." },
      { type: "callout", variant: "fun_fact", content: "The word 'Algorithm' comes from the name of a Persian mathematician, Muhammad ibn Musa al-Khwarizmi, who lived around 800 AD. He's often called the 'father of algebra' too!", icon: "📜" },
      { type: "key_term", title: "Algorithm", content: "A finite sequence of well-defined instructions to solve a specific problem. Every algorithm must have a clear beginning, a set of steps, and an end." },
      { type: "text", title: "Properties of a Good Algorithm", content: "Not every set of instructions qualifies as a good algorithm. A proper algorithm must be clear, have a definite start and end, produce the correct output, and work for all valid inputs." },
      { type: "step_by_step", title: "Five Properties of a Good Algorithm", items: ["Input — It takes zero or more inputs (information it needs to work with).", "Output — It produces at least one output (the result or answer).", "Definiteness — Every step must be clear and unambiguous. No guessing!", "Finiteness — It must end after a finite number of steps. It cannot run forever!", "Effectiveness — Each step must be doable and practical. No impossible tasks!"] },
      { type: "text", title: "Flowcharts: Visualizing Algorithms", content: "A flowchart is a diagram that shows the steps of an algorithm using special shapes. It's like a map for your solution — making it easy to see the path from start to finish. Flowcharts are especially useful when algorithms have decisions (yes/no choices)." },
      { type: "image", imageSrc: "/images/flowchart-symbols.png", imageAlt: "Common flowchart symbols — oval, rectangle, diamond, parallelogram", title: "Flowchart Symbols Guide" },
      { type: "step_by_step", title: "Flowchart Symbols", items: ["Oval (Rounded Rectangle) — Start and End points of the algorithm.", "Rectangle — A process step or action (e.g., 'Add two numbers').", "Diamond — A decision point with Yes/No branches (e.g., 'Is the number greater than 10?').", "Parallelogram — Input or Output (e.g., 'Read a number' or 'Display result').", "Arrow — Shows the flow direction from one step to the next."] },
      { type: "comparison", title: "Algorithm vs Flowchart vs Pseudocode", columns: { leftTitle: "Format", rightTitle: "Description", left: ["Algorithm (plain text)", "Flowchart (visual diagram)", "Pseudocode (structured text)"], right: ["Written steps in simple language — easy to write", "Shapes and arrows showing the flow — easy to visualize", "Code-like language but not real code — bridge between human and computer language"] } },
      { type: "key_term", title: "Pseudocode", content: "A way of writing algorithm steps in a structured format that looks like code but is written in plain language. It helps plan the logic before writing real code." },
      { type: "callout", variant: "tip", content: "Always plan your algorithm on paper before coding! Professional programmers spend more time planning (writing pseudocode and drawing flowcharts) than actually typing code.", icon: "✏️" },
      { type: "activity", title: "Activity: Write an Algorithm!", content: "Write an algorithm (in plain steps) and draw a flowchart for this problem: 'Check if a number entered by the user is even or odd.'", items: ["Step 1: Start", "Step 2: Take a number as input from the user", "Step 3: Divide the number by 2 and check the remainder", "Step 4: If remainder is 0, display 'Even'. Otherwise display 'Odd'", "Step 5: End", "Now draw this as a flowchart using the correct shapes!"] },
      { type: "summary", title: "Chapter Summary", content: "An algorithm is a step-by-step procedure to solve a problem. Good algorithms have clear inputs, outputs, definite steps, are finite, and effective. We can represent algorithms as plain text, flowcharts (visual diagrams with shapes), or pseudocode (structured text). Planning with algorithms makes coding easier and more organized." }
    ]
  },
  {
    classNum: 7,
    title: "Data All Around Us",
    subtitle: "Understanding Information & Representation",
    blocks: [
      { type: "text", title: "What is Data?", content: "Data is raw facts and figures — numbers, words, images, sounds, or any information that can be collected and processed. Right now, you're surrounded by data! The temperature outside, the time on the clock, the words in this book, and even the colors on this page — all of it is data." },
      { type: "callout", variant: "info", content: "There's a difference between Data and Information. Data is raw and unprocessed (like '37'). Information is data that has been processed and given meaning (like '37°C is the normal human body temperature').", icon: "📊" },
      { type: "key_term", title: "Data", content: "Raw, unorganized facts that can be in the form of numbers, text, images, audio, or video. Data becomes useful when it is processed and organized into information." },
      { type: "key_term", title: "Information", content: "Data that has been processed, organized, and given context so it becomes meaningful and useful for decision-making." },
      { type: "text", title: "Types of Data", content: "Not all data is the same! Different types of data need to be stored and processed differently. Understanding data types helps us organize and work with data more efficiently." },
      { type: "step_by_step", title: "Common Data Types", items: ["Numeric Data — Numbers used for calculations (e.g., age: 12, marks: 95, price: ₹250).", "Text Data (String) — Letters, words, and sentences (e.g., name: 'Arjun', city: 'Delhi').", "Boolean Data — Only two values: True or False, Yes or No (e.g., 'Is it raining?' → True).", "Image Data — Pictures and photographs stored as pixels (tiny colored dots).", "Audio Data — Sounds and music stored as digital wave patterns."] },
      { type: "text", title: "How Computers Store Data: Binary System", content: "Computers don't understand Hindi, English, or any human language. They only understand two things: ON and OFF, represented by 1 and 0. This is called the Binary System. Everything — every letter you type, every photo you see, every song you hear — is stored as combinations of 1s and 0s inside the computer!" },
      { type: "comparison", title: "Decimal vs Binary", columns: { leftTitle: "Decimal (Our System)", rightTitle: "Binary (Computer's System)", left: ["Uses digits 0-9", "Base 10 system", "0 = 0", "5 = 5", "10 = 10", "255 = 255"], right: ["Uses only 0 and 1", "Base 2 system", "0 = 0", "5 = 101", "10 = 1010", "255 = 11111111"] } },
      { type: "key_term", title: "Bit", content: "The smallest unit of data in computing — a single 0 or 1. 'Bit' stands for Binary Digit." },
      { type: "key_term", title: "Byte", content: "A group of 8 bits. One byte can represent a single character (like the letter 'A'). 1 KB = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB." },
      { type: "callout", variant: "fun_fact", content: "Your favorite 5-minute YouTube video is about 50 MB of data. That's approximately 400,000,000 (40 crore!) individual bits of 0s and 1s working together to show you the video!", icon: "🎬" },
      { type: "activity", title: "Activity: Convert to Binary!", content: "Try converting these decimal numbers to binary. Remember: keep dividing by 2 and note the remainders!", items: ["Convert 3 to binary (Answer: 11)", "Convert 7 to binary (Answer: 111)", "Convert 12 to binary (Answer: 1100)", "Convert 20 to binary (Answer: 10100)", "Bonus: How many bits does the number 255 need? (Answer: 8 bits = 1 byte!)"] },
      { type: "text", title: "Data Storage Units: From Tiny to Massive", content: "Just like we measure distances in meters and kilometers, we measure data in bits, bytes, kilobytes, and beyond. Understanding these units helps you appreciate how much data we generate and store every day." },
      { type: "image", imageSrc: "/images/sequence-steps.png", imageAlt: "Visual diagram showing data storage units from bits to terabytes", title: "Data Storage Units" },
      { type: "step_by_step", title: "Data Storage Units Ladder", items: ["1 Bit — A single 0 or 1. The smallest possible piece of data.", "1 Byte = 8 Bits — Enough to store one character like 'A' or '7'.", "1 Kilobyte (KB) = 1024 Bytes — About half a page of typed text.", "1 Megabyte (MB) = 1024 KB — A single high-quality photo or a short song.", "1 Gigabyte (GB) = 1024 MB — About 250 songs or 1 hour of HD video.", "1 Terabyte (TB) = 1024 GB — About 500 hours of movies. A whole library!"] },
      { type: "text", title: "Real-World Data: How Much Do We Generate?", content: "Every day, the world creates approximately 2.5 quintillion bytes (2.5 exabytes) of data! Every WhatsApp message, every Google search, every Instagram photo, and every YouTube video adds to this colossal amount. By the time you finish reading this page, the world will have created millions of gigabytes of new data." },
      { type: "callout", variant: "fun_fact", content: "If you stored 1 terabyte of data on printed paper, the stack would be over 16 km tall — taller than where commercial airplanes fly! That's why we use digital storage instead.", icon: "✈️" },
      { type: "comparison", title: "Analog vs Digital Data", columns: { leftTitle: "Analog Data", rightTitle: "Digital Data", left: ["Continuous signals (like sound waves)", "Can degrade with copying", "Examples: vinyl records, film photos", "Harder to edit and process", "Takes physical space to store"], right: ["Discrete values (0s and 1s)", "Perfect copies every time", "Examples: MP3 files, JPEG photos", "Easy to edit, search, and process", "Stored compactly on chips and drives"] } },
      { type: "key_term", title: "Pixel", content: "The smallest unit of a digital image. Each pixel stores color data. A 1920×1080 HD screen has over 2 million pixels, each one a tiny dot of color contributing to the full picture." },
      { type: "text", title: "How Images Are Stored as Data", content: "Every digital photo is really a grid of tiny colored squares called pixels. Each pixel's color is stored as a combination of Red, Green, and Blue (RGB) values — each ranging from 0 to 255. So one pixel needs 3 bytes (24 bits) of data. A 12-megapixel phone camera photo contains 12 million pixels — that's 36 million bytes just for color data!" },
      { type: "activity", title: "Practice Problem: Calculate Data Sizes", content: "Use what you've learned about data units to solve these real-world problems:", items: ["A text message has 160 characters. How many bytes is that? (Answer: 160 bytes)", "An image is 800×600 pixels. Each pixel uses 3 bytes (RGB). What's the uncompressed image size in MB? (Answer: 800×600×3 = 1,440,000 bytes ≈ 1.37 MB)", "Your phone has 64 GB storage. How many 4 MB photos can it hold? (Answer: 64×1024÷4 = 16,384 photos!)", "A song is 3.5 MB. How many songs fit on a 2 GB pen drive? (Answer: 2×1024÷3.5 ≈ 585 songs)", "Challenge: If you type at 40 words per minute and each word averages 5 characters, how many kilobytes of text do you produce in an hour? (Answer: 40×60×5 = 12,000 bytes ≈ 11.7 KB)"] },
      { type: "callout", variant: "tip", content: "Remember the trick: each storage unit is 1024 times the previous one, not 1000! This is because computers work in binary (powers of 2), and 2¹⁰ = 1024.", icon: "🧮" },
      { type: "summary", title: "Chapter Summary", content: "Data is raw facts (numbers, text, images, sounds) that becomes information when processed. Common data types include numeric, text, boolean, image, and audio. Computers store all data in binary (0s and 1s). A bit is a single binary digit, and 8 bits make a byte. Data storage ranges from tiny bytes to massive terabytes. Images are stored as pixel grids with RGB color values. Understanding data representation is fundamental to understanding how computers work!" }
    ]
  },
  {
    classNum: 8,
    title: "What is Artificial Intelligence?",
    subtitle: "When Machines Start to Think",
    blocks: [
      { type: "text", title: "Welcome to the World of AI!", content: "Artificial Intelligence, or AI, is the science of making machines that can think, learn, and make decisions — similar to how humans do! AI is one of the most exciting and important technologies of the 21st century. It's already changing how we live, work, play, and learn." },
      { type: "callout", variant: "info", content: "AI doesn't mean robots walking around like humans (that's science fiction — for now!). Most AI today is 'narrow AI' — it's really good at ONE specific task, like recognizing faces, translating languages, or recommending songs.", icon: "🤖" },
      { type: "key_term", title: "Artificial Intelligence (AI)", content: "The field of computer science focused on creating systems that can perform tasks that normally require human intelligence — such as understanding language, recognizing images, making decisions, and learning from experience." },
      { type: "text", title: "AI in Your Daily Life", content: "You might think AI is something futuristic, but you're already using it every day! Here are some common examples that might surprise you." },
      { type: "image", imageSrc: "/images/ai-applications.png", imageAlt: "AI applications in daily life — voice assistants, self-driving cars, smart home", title: "AI in Everyday Life" },
      { type: "step_by_step", title: "AI Examples You Use Daily", items: ["Voice Assistants — Siri, Alexa, Google Assistant understand your voice and respond intelligently.", "Auto-Correct & Predictive Text — Your phone predicts what you're typing and fixes spelling mistakes.", "YouTube & Netflix Recommendations — AI analyzes what you watch and suggests videos you might like.", "Face Unlock — Your phone recognizes YOUR face among billions of possible faces.", "Google Search — AI understands your question, even if you type it with mistakes, and finds the best answers.", "Instagram & Snapchat Filters — AI detects your face and adds fun effects in real-time."] },
      { type: "comparison", title: "Human Intelligence vs Artificial Intelligence", columns: { leftTitle: "Human Intelligence", rightTitle: "Artificial Intelligence", left: ["Learns from experience and emotions", "Can be creative and imaginative", "Gets tired and needs rest", "Makes mistakes due to feelings", "Can do many different tasks"], right: ["Learns from data and patterns", "Follows rules and patterns (limited creativity)", "Never gets tired, works 24/7", "Consistent but can have data bias", "Usually excels at one specific task"] } },
      { type: "key_term", title: "Machine Learning (ML)", content: "A subset of AI where machines learn from data and improve over time WITHOUT being explicitly programmed for every scenario. Instead of writing rules, we give the machine examples and it learns the rules itself!" },
      { type: "text", title: "The Turing Test", content: "In 1950, a brilliant mathematician named Alan Turing asked a simple question: 'Can machines think?' He proposed a test: if a human talks to a machine (through text) and cannot tell whether they're talking to a human or a machine, then the machine passes the Turing Test. Modern chatbots like ChatGPT are getting remarkably close!" },
      { type: "callout", variant: "fun_fact", content: "Alan Turing is often called the 'Father of Computer Science.' During World War II, he built a machine that cracked the Nazi 'Enigma' code, helping to end the war sooner and saving millions of lives!", icon: "🏆" },
      { type: "key_term", title: "Turing Test", content: "A test proposed by Alan Turing to determine if a machine can exhibit intelligent behavior indistinguishable from a human. If a judge can't tell machine from human in a text conversation, the machine passes." },
      { type: "activity", title: "Activity: AI or Not AI?", content: "For each of these, decide: Is it using AI or just regular programming? Discuss your answers with a classmate!", items: ["A calculator that adds two numbers (Not AI — follows fixed rules)", "A spam filter that learns which emails are junk (AI — learns from data!)", "A traffic light that changes every 60 seconds (Not AI — fixed timer)", "A self-driving car that avoids obstacles (AI — makes real-time decisions!)", "A chatbot that answers your questions naturally (AI — understands language!)"] },
      { type: "summary", title: "Chapter Summary", content: "Artificial Intelligence is about making machines that can perform tasks requiring human-like intelligence. AI is already in our daily lives through voice assistants, recommendations, face recognition, and more. Machine Learning allows machines to learn from data. The Turing Test helps us think about whether machines can truly 'think.' AI is powerful but currently limited to specific tasks (narrow AI)." }
    ]
  },
  {
    classNum: 9,
    title: "How Machines Learn",
    subtitle: "The Magic Behind Machine Learning",
    blocks: [
      { type: "text", title: "From Rules to Learning", content: "Traditional programming is like giving someone a detailed recipe — you tell the computer exactly what to do for every situation. Machine Learning (ML) flips this around: instead of giving rules, you give the computer lots of examples (data), and it figures out the rules on its own! This is a fundamental shift in how we build intelligent systems." },
      { type: "callout", variant: "info", content: "Think of it this way: Traditional Programming = Data + Rules → Answer. Machine Learning = Data + Answers → Rules! The machine learns the rules by studying examples.", icon: "🔄" },
      { type: "key_term", title: "Machine Learning", content: "A branch of AI where computers learn patterns from data and make predictions or decisions without being explicitly programmed with rules for every scenario." },
      { type: "key_term", title: "Training Data", content: "The collection of examples (data) used to teach a machine learning model. The quality and quantity of training data directly affects how well the model learns." },
      { type: "text", title: "Types of Machine Learning", content: "Just like there are different ways humans learn (from teachers, from experience, from trial and error), machines also have different learning approaches. The three main types are supervised, unsupervised, and reinforcement learning." },
      { type: "image", imageSrc: "/images/brain-thinking.png", imageAlt: "Machine learning types — supervised, unsupervised, reinforcement learning", title: "Types of Machine Learning" },
      { type: "step_by_step", title: "Three Types of Machine Learning", items: ["Supervised Learning — The machine learns from labeled examples. Like a teacher showing you solved problems. Example: Showing 1000 photos labeled 'cat' or 'dog' so the machine learns to tell them apart.", "Unsupervised Learning — The machine finds hidden patterns in data WITHOUT labels. Like sorting a bag of mixed candies into groups by color/shape without being told the categories. Example: Customer grouping in marketing.", "Reinforcement Learning — The machine learns by trial and error, getting rewards for good actions and penalties for bad ones. Like training a puppy — treats for sitting, no treats for jumping. Example: Teaching a game-playing AI."] },
      { type: "comparison", title: "Supervised vs Unsupervised Learning", columns: { leftTitle: "Supervised Learning", rightTitle: "Unsupervised Learning", left: ["Uses labeled data (answers given)", "Teacher guides the learning", "Predicts specific outcomes", "Example: Email spam detection", "Example: Image classification"], right: ["Uses unlabeled data (no answers)", "Machine discovers patterns alone", "Finds hidden structures in data", "Example: Customer segmentation", "Example: Anomaly detection"] } },
      { type: "text", title: "How a Model Learns: The Training Process", content: "Training a machine learning model is like studying for an exam. First, the model sees many examples (training). Then it's tested on new examples it hasn't seen before (testing). If it makes mistakes, it adjusts its understanding and tries again. This cycle repeats thousands of times until the model becomes accurate!" },
      { type: "key_term", title: "Model", content: "The mathematical representation that a machine learning algorithm builds after learning from training data. It's the 'brain' that makes predictions on new, unseen data." },
      { type: "key_term", title: "Accuracy", content: "A measure of how often the model makes correct predictions. For example, 95% accuracy means the model is correct 95 out of 100 times." },
      { type: "callout", variant: "fun_fact", content: "Google Photos uses machine learning trained on billions of images. It can recognize your face, your pet, and even specific landmarks — all because it learned patterns from massive amounts of data!", icon: "📸" },
      { type: "activity", title: "Activity: Train Your Classmate!", content: "Play a 'Human Machine Learning' game! One person is the 'machine' and the other is the 'trainer.'", items: ["Trainer: Draw 10 shapes on paper — some circles, some squares (label each one)", "Machine: Look at the labeled examples and try to learn the difference", "Trainer: Now draw 5 NEW shapes without labels", "Machine: Predict if each new shape is a circle or square", "Check accuracy: How many did the 'machine' get right out of 5?", "Discuss: What if the training data had errors? Would it affect predictions?"] },
      { type: "summary", title: "Chapter Summary", content: "Machine Learning allows computers to learn from data instead of being explicitly programmed. The three main types are Supervised (labeled data), Unsupervised (unlabeled data), and Reinforcement (reward-based) learning. Models are trained through repeated cycles of learning and testing. Training data quality is crucial — bad data leads to bad models! ML powers many modern applications from photo recognition to language translation." }
    ]
  },
  {
    classNum: 10,
    title: "AI in the Real World",
    subtitle: "Applications, Ethics & the Future",
    blocks: [
      { type: "text", title: "AI: Transforming Every Industry", content: "Artificial Intelligence is no longer just a concept from science fiction — it's actively transforming every industry and aspect of our lives. From healthcare to education, transportation to entertainment, AI is creating solutions to problems we once thought impossible. Understanding how AI is applied in the real world helps us appreciate its power and prepare for an AI-driven future." },
      { type: "callout", variant: "info", content: "By 2030, AI is expected to contribute over $15.7 trillion to the global economy — more than the current GDP of China and India combined! India alone could see a $957 billion boost from AI adoption.", icon: "🌍" },
      { type: "text", title: "AI in Healthcare", content: "AI is revolutionizing medicine by helping doctors diagnose diseases earlier and more accurately. AI systems can analyze medical images (X-rays, MRIs, CT scans) and detect cancers, fractures, and other conditions — sometimes more accurately than experienced doctors! AI is also accelerating drug discovery, reducing the time to develop new medicines from years to months." },
      { type: "step_by_step", title: "AI Applications Across Industries", items: ["Healthcare — Disease diagnosis, drug discovery, personalized treatment plans, robot-assisted surgery.", "Education — Adaptive learning platforms (like this one!), automated grading, personalized study paths, intelligent tutoring.", "Transportation — Self-driving cars, traffic optimization, route planning, drone deliveries.", "Finance — Fraud detection, algorithmic trading, credit scoring, chatbot customer service.", "Agriculture — Crop disease detection, yield prediction, automated irrigation, drone monitoring.", "Entertainment — Movie/music recommendations, AI-generated art, game development, deepfakes."] },
      { type: "comparison", title: "AI Benefits vs Challenges", columns: { leftTitle: "Benefits of AI", rightTitle: "Challenges & Concerns", left: ["Saves time and increases efficiency", "Reduces human error in critical tasks", "Available 24/7, never gets tired", "Can process huge amounts of data", "Creates new jobs and industries"], right: ["May replace certain jobs", "Bias in AI if training data is biased", "Privacy concerns with data collection", "High energy consumption for training", "Ethical dilemmas in decision-making"] } },
      { type: "key_term", title: "AI Ethics", content: "The study of moral principles and guidelines for the development and use of AI systems. It addresses fairness, transparency, privacy, accountability, and the social impact of AI technology." },
      { type: "key_term", title: "Bias in AI", content: "When an AI system produces unfair or prejudiced results because its training data contains existing societal biases. For example, a hiring AI trained mostly on male resumes might unfairly reject female candidates." },
      { type: "text", title: "Responsible AI: The FATE Framework", content: "As AI becomes more powerful, we need to ensure it's developed and used responsibly. The FATE framework gives us four key principles to evaluate AI systems and ensure they benefit everyone." },
      { type: "step_by_step", title: "The FATE Framework", items: ["Fairness — AI should treat all people equally, regardless of race, gender, age, or background. No discrimination!", "Accountability — Someone must be responsible when AI makes mistakes. We can't just blame the machine.", "Transparency — People should understand HOW an AI makes its decisions. No 'black box' systems!", "Ethics — AI should be developed with strong moral principles, respecting human rights, privacy, and dignity."] },
      { type: "callout", variant: "tip", content: "As future AI creators and users, remember: AI is a tool created by humans. It reflects our values and biases. The responsibility to make AI fair, ethical, and beneficial lies with US — the humans who design, train, and deploy it.", icon: "⚖️" },
      { type: "text", title: "Career Paths in AI", content: "AI is creating exciting new career opportunities. Whether you love math, art, medicine, or law, there's a place for you in the AI world!" },
      { type: "step_by_step", title: "Exciting AI Career Paths", items: ["AI/ML Engineer — Design and build AI systems and machine learning models.", "Data Scientist — Analyze large datasets to extract insights and build predictive models.", "AI Ethics Officer — Ensure AI systems are fair, transparent, and responsible.", "Robotics Engineer — Build intelligent robots for manufacturing, healthcare, and exploration.", "NLP Specialist — Work on systems that understand and generate human language.", "AI Product Manager — Bridge the gap between technical AI teams and business needs."] },
      { type: "activity", title: "Activity: Design an AI Solution!", content: "Choose a real-world problem in your community or school. Design an AI-powered solution for it!", items: ["Identify a problem (e.g., food waste in school canteen, traffic near school, water wastage)", "What data would your AI need? List at least 5 data points", "What type of ML would you use? (Supervised/Unsupervised/Reinforcement)", "What ethical concerns should you consider?", "Draw a simple flowchart of how your AI solution would work", "Present your idea to your class — would they use it?"] },
      { type: "text", title: "AI in India: A Growing Revolution", content: "India is emerging as a global AI powerhouse. With the world's largest youth population, a booming tech industry, and government initiatives like 'AI for All,' India is uniquely positioned to lead the AI revolution. Indian companies and startups are using AI to solve uniquely Indian challenges — from predicting monsoon patterns for farmers to enabling healthcare in remote villages." },
      { type: "image", imageSrc: "/images/ai-applications.png", imageAlt: "AI applications across Indian industries — agriculture, healthcare, education, smart cities", title: "AI Transforming India" },
      { type: "step_by_step", title: "AI Success Stories from India", items: ["Microsoft AI for Agriculture — Helps Indian farmers predict crop yields and optimize sowing times using weather and soil data.", "Niramai — An Indian startup using AI to detect breast cancer through a simple, affordable thermal scan instead of expensive mammograms.", "NITI Aayog's AI Strategy — India's government think tank launched a national AI strategy focusing on healthcare, agriculture, education, smart cities, and mobility.", "Google Flood Forecasting — AI-powered flood prediction system that warns communities in Bihar and UP days before floods arrive, saving thousands of lives.", "Byju's & Kode Intel — AI-powered adaptive learning platforms that personalize education for millions of Indian students."] },
      { type: "callout", variant: "fun_fact", content: "India produces the second-highest number of AI research papers in the world, after China! Indian AI researchers are contributing to breakthroughs in natural language processing, computer vision, and healthcare AI.", icon: "🇮🇳" },
      { type: "text", title: "The AI Decision-Making Process", content: "When an AI system makes a decision — like approving a loan, filtering a job application, or diagnosing a disease — it follows a systematic process. Understanding this process helps us evaluate AI systems critically and identify potential problems." },
      { type: "step_by_step", title: "How AI Makes a Decision (Step by Step)", items: ["Data Collection — Gather relevant data (patient records, financial history, images, etc.).", "Data Preprocessing — Clean the data: remove errors, fill in missing values, normalize formats.", "Feature Extraction — Identify the most important variables (features) that influence the decision.", "Model Processing — The trained model analyzes features and calculates probabilities for each outcome.", "Prediction/Decision — The model outputs its decision along with a confidence score (e.g., '92% likely spam').", "Human Review (Critical Cases) — For high-stakes decisions, a human expert reviews the AI's recommendation."] },
      { type: "comparison", title: "Strong AI vs Weak AI vs Super AI", columns: { leftTitle: "Type", rightTitle: "Description", left: ["Weak (Narrow) AI", "Strong (General) AI", "Super AI"], right: ["Excels at ONE specific task. Exists TODAY. Examples: Siri, chess engines, spam filters.", "Can perform ANY intellectual task a human can. Does NOT exist yet. Would need human-like understanding.", "Would surpass ALL human intelligence. Purely theoretical. Raises deep philosophical questions about consciousness."] } },
      { type: "key_term", title: "Deep Learning", content: "A subset of machine learning inspired by the human brain's neural networks. It uses layers of artificial neurons to learn complex patterns. Deep learning powers image recognition, voice assistants, and language translation." },
      { type: "key_term", title: "Natural Language Processing (NLP)", content: "The branch of AI that helps computers understand, interpret, and generate human language. NLP powers chatbots, translation apps, voice assistants, and auto-correct features." },
      { type: "activity", title: "Practice Problem: AI Ethics Case Studies", content: "Read each scenario and discuss the ethical implications with your classmates. There are no 'right' answers — the goal is critical thinking!", items: ["An AI hiring tool rejects 80% of female candidates because it was trained on 10 years of data from a male-dominated company. Is this the AI's fault or the company's? What should be done?", "A self-driving car must choose between hitting a pedestrian or swerving into a wall (injuring the passenger). Who should make this decision — the AI, the company, or the government?", "A school uses AI to predict which students are 'at risk' of failing. A student flagged as 'at risk' feels unfairly labeled and demotivated. Should the school share these predictions with students?", "An AI art generator creates paintings in the style of a living artist without permission. Is this theft, inspiration, or something else entirely?", "A country uses facial recognition AI to monitor all citizens in public spaces for 'safety.' Where should the line be drawn between security and privacy?"] },
      { type: "callout", variant: "tip", content: "When evaluating any AI system, always ask these four questions: (1) What data was it trained on? (2) Who benefits and who might be harmed? (3) Is there human oversight? (4) Can the decision be explained?", icon: "🔍" },
      { type: "summary", title: "Chapter Summary", content: "AI is transforming industries from healthcare to agriculture, education to entertainment. India is emerging as a global AI leader with innovative applications in farming, healthcare, and education. While AI offers tremendous benefits (efficiency, accuracy, innovation), it also raises challenges (bias, privacy, job displacement). Understanding Strong vs Weak vs Super AI helps us set realistic expectations. The FATE framework (Fairness, Accountability, Transparency, Ethics) guides responsible AI development. Deep learning and NLP are key technologies powering modern AI. As future AI leaders, we must think critically about AI's impact and ensure it benefits all of humanity." }
    ]
  }
];

export const getSampleChapterForClass = (classNum: number): SampleChapter | undefined => {
  return sampleBookChapters.find(ch => ch.classNum === classNum);
};
